### ISSUE TITLE
Bottom overflowed by 185 pixels

### ISSUE THREAD

**Issue by SinghTanisha16** [afgprogrammer/Flutter-Login-Page-UI#2]
I was trying to tum it on Redmi 6 pro and it gave me the error that 

> bottom overflowed by 185 pixels.

**Comment by afgprogrammer** [comment]
Try this: Scaffold(resizeToAvoidBottomPaddin:false)

**Comment by SinghTanisha16** [comment]
Didn’t worked. Still facing the problem. After clicking on the textbox, bottom overflowed by 185 pixels and then I cant scroll.

**Comment by afgprogrammer** [comment]
Ok, I got it. I will fix it.

**Comment by Tejas-gaikwad** [comment]
I a =m getting this error...

The method 'FadeAnimation' isn't defined for the type 'HomePage'.
