### ISSUE TITLE
Error: The operator '[]' isn't defined for the class in FadeAnimation class

### ISSUE THREAD

**Issue by OrchiDorchi** [afgprogrammer/Flutter-Login-Page-UI#3]
When I try to add animations, I get the error below. Can you help me?
`Error: The operator '[]' isn't defined for the class 'Object?'.
lib/Animations/fade_animation.dart:26
'Object' is from 'dart:core'.
Try correcting the operator to an existing operator, or defining a '[]' operator.
        opacity: animation["opacity"],
`
in here:
![image](https://user-images.githubusercontent.com/55514449/147295476-f8d6abe9-dcd0-4708-8756-359567608f6b.png)

**Comment by rastappopouloss** [comment]
**I have the problem....**

**Comment by afgprogrammer** [comment]
@OrchiDorchi Check out this file ->
https://github.com/afgprogrammer/Flutter-job-list-application/blob/master/lib/animation/FadeAnimation.dart
